project_id = "pqfvjfpyqtinobpitnft"

[functions.generate-image]
verify_jwt = true

[functions.create-abacate-checkout]
verify_jwt = true

[functions.abacate-webhook]
verify_jwt = false

[functions.confirm-abacate-billing]
verify_jwt = true

